---
  - name: install default packages
    apt: pkg={{ item }} state=installed
    with_items:
      - vim
      - build-essential
      - git
      - wget
      - zsh
      - unzip
      - curl
      - sqlite3 
      - libsqlite3-dev
