---
# https://gist.github.com/tsabat/1498393
- name: See if zsh is installed
  stat: path=~/.oh-my-zsh
  register: zsh_installed

- name: zsh
  apt: pkg=zsh
  sudo: yes

- name: install oh my zsh
  shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
  when: not zsh_installed.stat.exists

- name: zshrc config
  copy: src=zshrc dest=~/.zshrc

- name: set zsh as the shell
  user: name=$user shell=/usr/bin/zsh
  sudo: true

# Courtsey: https://github.com/markmandel/dotfiles/blob/master/provision/roles/core/tasks/_oh_my_zsh.yml
