---
- name: Add PHP Repository
  apt_repository: repo='ppa:ondrej/php5-5.6' state=present
  register: ppaphp

- name: Install PHP
  register: phpinstall
  when: ppaphp|success
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
   - php5-cli
   - php5-pgsql
   - php5-mysql
   - php5-sqlite
   - php5-curl
   - php5-gd
   - php5-mcrypt
   - php5-memcached
   - php5-intl

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer

- name: Rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: Make Composer Executable
  shell: chmod a+x /usr/local/bin/composer

- name: Composer Self Update
  shell: composer self-update
